services:
  - type: web
    name: course-survivors
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
    disk:
      name: sqlite-data
      mountPath: /var/data
      sizeGB: 1